Repository Code-Social/official-website, pull requests merged in 2024-10, with the labels that each got.

#24 Navigation padding issue
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#81 Updated Icons In the code social website
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#67 added event calendar and dark mode on the top right corner
  .vscode/settings.json
  darkmode.js
  images/light.png
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#60 HTML Changes, Script.js Changes
  index.html
  script.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#106 navbar ,dropdowns, theme mode buttons updated.
  images/gitHub.png
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#64 Added Footer Section with Social Icons
  images/logo1.svg
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#159 Revert "Enhanced Event Calendar"
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#147 [Fixed]: Logo & Social Icon
  images/discord.png
  images/github_new.png
  images/linkedin.png
  images/logo1.svg
  images/whatsapp.png
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#160 Enhanced Event Calendar
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#174 Improved Event Form UI with Enhanced Styling and Animated Color Picker
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#173 Updated Favicon in the website
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#105 Added Learning section
  index.html
  learning.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#207 Solved all the merge conflicts arising and Calendar issue fixed issue #187
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#208 ASsigment #206 done
  images/favicon.png
  images/icon.png
  images/logo copy.png
  index.html
  login.html
  signup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#211 Update darkmode.js
  darkmode.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#221 Fixed text color issue ! #220
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#228 fixed the navbar issue and made it look better issue #223
  images/mentor1.jpg
  images/mentor2.jpg
  images/mentor3.jpg
  index.html
  link.txt
  mentor.css
  mentorship.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#243 Fixed images not loading issue ! #222
  404.html
  index.html
  maintenance.html
  script.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#253 Added Volunteer Opportunities Webpage
  images/volunteer-bg.jpg
  index.html
  volunteering-oppurtunities/vol-effects.js
  volunteering-oppurtunities/vol-style.css
  volunteering-oppurtunities/volunteer-opp-page.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#260 Feat2:fixed the blog section and now can be merged
  blog.css
  blog.html
  blogs/1.json
  blogs/2.json
  blogs/3.json
  blogs/4.json
  images/b1.jpeg
  images/b2.jpg
  images/b4.jpeg
  images/beg.jpg
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#274 ✨chatbot added ✨
  blog.html
  index.html
  learning.html
  login.html
  maintenance.html
  mentorship.html
  signup.html
  volunteering-oppurtunities/volunteer-opp-page.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#254 Navbar Changes
  darkmode.js
  script.js
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#287 fix: correct image loading for toggle button in light/dark mode
  darkmode.js
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#310 blog page updated
  blog.css
  blog.html
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#285 [Fix]- Footer Alignment and Position Issues
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#323 resolve the dropdown hidden feature #322
  404.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#325 Text visible now in Event title #321
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#330 [Feat]- Student Tech Resources and Footer Fix
  Resources.css
  Resources.html
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#327 Added a trailing cursor effect for enhanced user interaction
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#340 Bug331 solved
  blog.css
  blog.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#349 update learning page
  learning.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#348 about-section-styling
  images/about-img.png
  package-lock.json
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#370 Update README.md added Stargazers and Forkers section
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#364 [FIXED] Feature: Adding a registration page for live events #361
  index.html
  register.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#371 fixed dark mode toggle for footer section
  darkmode.js
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#386 Enhanced the UI of Webpage by making changes in it .
  index.html
Labels: level3

#408 Correcting index.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#379 Disable and restrict 'Add Event' button for past dates
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#412 fix: dark mode enabled in maintenance.html
  index.html
  maintenance.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#397 feat: added navbar and footer to Resources.html
  Resources.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#420 Removed the blogs section ,shifted the live events in the navbar to a little right.
  blog.css
  blog.html
  index.html
  learning.html
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#430 Added Event page with redirect link in navbar and footer
  Resources.html
  events.html
  eventstyle.css
  images/Green.jpeg
  images/blue.jpeg
  images/event1.jpg
  images/header.jpg
  images/red.jpeg
  images/yellow.jpeg
  index.html
  learning.html
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#429 enhancement: added new navbar and footer pages that can be used across all pages
  common.js
  darkmode.js
  footer.html
  index.html
  navbar.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#463 [Feat]-Join Our Team Page Added
  JoinTeam.css
  JoinTeam.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#462 changed gitHub icon image
  images/gitHub.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#445 Added table of contents to README
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#447 Chatbot Icon overlaps with Scroll to top button #421
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#471 fix: fixes nav bar visibility in light mode
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level2
